defaults:
  - base_dataset
  - view_sampler: arbitrary
  - optional view_sampler_dataset_specific_config@view_sampler: arbitrary_scannet

name: scannet
roots: [/ssdwork/datasets/scannet]
make_baseline_1: true
augment: true

input_image_shape: [256, 256]
original_image_shape: [720, 960]
cameras_are_circular: false

baseline_min: 1e-3
baseline_max: 1e2
max_fov: 120.0

